version: "3"
services:
  flume:
    build:
      context: ./services/flume
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./code/localhost/flume/:/var/flume/
    command:
      - /bin/bash
      - -c
      - |
        flume-ng agent -n a1 -c /opt/flume/conf -f /var/flume/conf/test.conf -Dflume.root.logger=INFO,console
  zookeeper:
    image: wurstmeister/zookeeper
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./data/zookeeper:/opt/zookeeper-3.4.13/data
    ports:
      - 2182:2181
  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    environment:
      - KAFKA_BROKER_ID=0
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=INSIDE://:9092,OUTSIDE://:9093
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka:9092,OUTSIDE://localhost:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
      - JMX_PORT=9999
      - TZ=Asia/Shanghai
    volumes:
      - ./data/kafka:/kafka
    ports:
      - 9092:9092
      - 9093:9093
      - 9999:9999
    depends_on:
      - zookeeper
  efak:
    build:
      context: ./services/efak
    environment:
      - EFAK_CLUSTER_ZK_LIST=zookeeper:2181
      - TZ=Asia/Shanghai
    ports:
      - "8048:8048"
    depends_on:
      - kafka


